spring:
  # Mysql
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/ptj
    username: root
    password: root

    # flyway설정
  flyway:
    enabled: true
    baseline-on-migrate: true

  # JSP
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# Mybatis
mybatis:
  # mapper location
  mapper-locations: classpath:mappers/*/*.xml
  # column name to camel case
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.job.com.job.dashboard: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

image:
  upload:
    dir: C:/STUDY/workspace/img

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

kakao:
  auth-url: "https://kauth.kakao.com/oauth/authorize"
  token-url: "https://kauth.kakao.com/oauth/token"
  user-info-url: "https://kapi.kakao.com/v2/user/me"
  client-id: "edd0be297e8b2b3f4147902b858d4b18"
  redirect-uri: "http://localhost:8080/user/kakao/login"
  client-secret: "57U4j6jgipImquildgBymVr4gk5X77d6"
