<div class="icon-container">
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-add-user"></i>flaticon-add-user</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-play-button"></i>flaticon-play-button</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-tick"></i>flaticon-tick</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-smartphone"></i>flaticon-smartphone</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-map"></i>flaticon-map</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-binoculars"></i>flaticon-binoculars</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-like"></i>flaticon-like</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-controls"></i>flaticon-controls</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-clock"></i>flaticon-clock</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-placeholder"></i>flaticon-placeholder</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-users"></i>flaticon-users</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-list"></i>flaticon-list</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-desktop"></i>flaticon-desktop</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-toy"></i>flaticon-toy</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-mortarboard"></i>flaticon-mortarboard</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-doc"></i>flaticon-doc</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-pdf"></i>flaticon-pdf</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-apartment"></i>flaticon-apartment</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-coding"></i>flaticon-coding</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-shipped"></i>flaticon-shipped</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-trophy"></i>flaticon-trophy</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-taxi"></i>flaticon-taxi</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-team"></i>flaticon-team</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-bar-chart"></i>flaticon-bar-chart</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-bell"></i>flaticon-bell</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-hand-shake"></i>flaticon-hand-shake</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-fast-food"></i>flaticon-fast-food</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-medal"></i>flaticon-medal</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-man"></i>flaticon-man</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-doctor"></i>flaticon-doctor</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-group"></i>flaticon-group</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-list-1"></i>flaticon-list-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-loupe"></i>flaticon-loupe</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-love"></i>flaticon-love</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-worker"></i>flaticon-worker</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-businessman"></i>flaticon-businessman</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-team-1"></i>flaticon-team-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-tshirt"></i>flaticon-tshirt</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-creative"></i>flaticon-creative</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-shield"></i>flaticon-shield</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-vector"></i>flaticon-vector</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-smile"></i>flaticon-smile</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-personal-profile"></i>flaticon-personal-profile</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-application"></i>flaticon-application</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-conversation"></i>flaticon-conversation</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-interview"></i>flaticon-interview</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-interview-1"></i>flaticon-interview-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-resume"></i>flaticon-resume</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-job"></i>flaticon-job</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-approval"></i>flaticon-approval</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-conversation-1"></i>flaticon-conversation-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-profiles"></i>flaticon-profiles</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-recruitment"></i>flaticon-recruitment</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-contract"></i>flaticon-contract</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-certificate"></i>flaticon-certificate</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-curriculum"></i>flaticon-curriculum</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-check-list"></i>flaticon-check-list</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-video-conference"></i>flaticon-video-conference</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-appointment"></i>flaticon-appointment</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-time"></i>flaticon-time</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-hired"></i>flaticon-hired</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-job-1"></i>flaticon-job-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-hiring"></i>flaticon-hiring</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-hiring-1"></i>flaticon-hiring-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-selection"></i>flaticon-selection</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-microphone"></i>flaticon-microphone</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-career"></i>flaticon-career</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-notification"></i>flaticon-notification</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-interview-2"></i>flaticon-interview-2</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-job-2"></i>flaticon-job-2</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-thinking"></i>flaticon-thinking</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-resume-1"></i>flaticon-resume-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-video-conference-1"></i>flaticon-video-conference-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-handshake"></i>flaticon-handshake</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-rating"></i>flaticon-rating</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-clothes"></i>flaticon-clothes</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-job-3"></i>flaticon-job-3</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-interview-3"></i>flaticon-interview-3</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-recruitment-1"></i>flaticon-recruitment-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-briefcase"></i>flaticon-briefcase</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-skills"></i>flaticon-skills</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-approved"></i>flaticon-approved</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-salary"></i>flaticon-salary</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-contact"></i>flaticon-contact</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-position"></i>flaticon-position</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-strategy"></i>flaticon-strategy</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-man-1"></i>flaticon-man-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-women"></i>flaticon-women</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-interview-4"></i>flaticon-interview-4</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-selection-process"></i>flaticon-selection-process</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-salary-1"></i>flaticon-salary-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-balance"></i>flaticon-balance</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-account"></i>flaticon-account</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-promotion"></i>flaticon-promotion</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-chat"></i>flaticon-chat</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-manager"></i>flaticon-manager</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-debit-card"></i>flaticon-debit-card</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-mortarboard-1"></i>flaticon-mortarboard-1</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-suitcase"></i>flaticon-suitcase</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-check-in"></i>flaticon-check-in</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-headhunting"></i>flaticon-headhunting</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-focus"></i>flaticon-focus</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-money"></i>flaticon-money</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-coin"></i>flaticon-coin</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-headphones"></i>flaticon-headphones</div>
    <div class="icon-item"><i class="font-xll text-primary align-self-center flaticon-mortgage"></i>flaticon-mortgage</div>
</div>
